version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - NODE_ENV=production
    container_name: retro-pop-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    volumes:
      - ../public:/app/public
    networks:
      - retro-pop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  retro-pop-network:
    driver: bridge
